project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Programming"
  author: "Jane Doe & John Doe"
  date: "`r Sys.Date()`"
  description: "A workshop introducing you to the Y Programming language"
  chapters:
    - index.qmd
    - 00-demo.qmd
    - 01-intro.qmd
    - 99-next-steps.qmd
    - references.qmd
  logo: files/logo.png
  sidebar:
    tools:
      - icon: box-arrow-up-right
        href: https://lukas-juergensmeier.com/
  github-repo: lukas-jue/course-website-template

bibliography: references.bib

format:
  html:
    css: [css/custom-environments.css, css/fontawesome/css/all.css]
    theme: cosmo



